CREATE TABLE PRODUCTOS3 (SECCION VARCHAR(20), NOMBREARTICULO VARCHAR(20), FECHA VARCHAR(20), PAISDEORIGEN VARCHAR(20), PRECIO FLOAT(20));

INSERT INTO PRODUCTOS3 (SECCION, NOMBREARTICULO, FECHA, PAISDEORIGEN, PRECIO)
VALUES ("DEPORTE", "Raqueta Wilson", "4/9/1998", "Holanda", 340.5), ("JUGUETERÍA", "Muñeca de princesas", "1/10/1998","China", 15.45);
